services:
  mirotalksfu:
    image: mirotalk/sfu:latest
    container_name: mirotalksfu
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3010:3010"                    # app/http (Coolify will proxy 443 -> 3010)
      - "40000-40100:40000-40100/udp"  # WebRTC media (UDP)
      - "40000-40100:40000-40100/tcp"  # TCP fallback (optional)
